### ISSUE TITLE
Event Smart (MENW): Critical error while adding New Event and New Person.

### ISSUE THREAD

**Issue by Saam01** [eventespresso/eea-people-addon#18] opened 2022-08-19 07:55 UTC
While we go to Event Smart > People Admin and click on Add person we see an error.
The error is also showing while adding any Event.

## Issue Overview

https://user-images.githubusercontent.com/99984614/185570873-15644d39-37f7-4df0-a7b7-cc0bfb9c8f0f.mp4

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

-Version of EE core: Event Smart
 - Version of WordPress: 5.6.8
 - Browser: Chrome
 - Website: https://makeeventsnotwar.com/

**Comment by tn3rb** [comment] 2022-08-19 17:23
pushed a fix to MENW

@Saam01 
in the future, can you plz copy n paste those stack traces for an error into the issue. The video is great because it helps show exactly what is happening, but direct access to the stack trace will help us developers even more. Thanks

**Comment by Saam01** [comment] 2022-08-19 17:42
@tn3rb 
Sure, I'll keep that in mind and post the error text with the Video/screenshot.

**Comment by garthkoyle** [comment] 2022-10-10 16:20
@Saam01 will you check this issue is fixed? I cannot reproduce it on MENW now.

**Comment by Saam01** [comment] 2022-10-11 12:17
I got another error when I go to People admin and now I cannot see the add people button:

https://user-images.githubusercontent.com/99984614/195087387-8fd992d9-ed37-4e4e-ab39-bb5a6ac3e1bc.mp4

**Comment by garthkoyle** [comment] 2022-10-11 16:45
Yes, here is the link to the page: https://august2022update.makeeventsnotwar.com/wp-admin/admin.php?page=espresso_people

**Comment by garthkoyle** [comment] 2022-10-31 20:02
This is no longer happening on MENW.

**Closed by garthkoyle** 2022-10-31 20:02 UTC
